/*
 * This file is generated by jOOQ.
 */
package ua.worktimekeeper.model.dayoff;


import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import ua.worktimekeeper.model.dayoff.tables.Holidays;
import ua.worktimekeeper.model.dayoff.tables.Request;
import ua.worktimekeeper.model.dayoff.tables.RequestType;
import ua.worktimekeeper.model.dayoff.tables.UserDetails;
import ua.worktimekeeper.model.dayoff.tables.UserGroupMapping;
import ua.worktimekeeper.model.dayoff.tables.UserGroups;
import ua.worktimekeeper.model.dayoff.tables.UserManagerMapping;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index HOLIDAYS_PK = Indexes0.HOLIDAYS_PK;
    public static final Index REQUEST_PK = Indexes0.REQUEST_PK;
    public static final Index REQUEST_TYPE_PK = Indexes0.REQUEST_TYPE_PK;
    public static final Index USER_DETAILS_PK = Indexes0.USER_DETAILS_PK;
    public static final Index USER_GROUP_MAPPING_PK = Indexes0.USER_GROUP_MAPPING_PK;
    public static final Index GROUPS_PK = Indexes0.GROUPS_PK;
    public static final Index USER_MANAGER_MAPPING_PK = Indexes0.USER_MANAGER_MAPPING_PK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index HOLIDAYS_PK = Internal.createIndex("holidays_pk", Holidays.HOLIDAYS, new OrderField[] { Holidays.HOLIDAYS.H_ID }, true);
        public static Index REQUEST_PK = Internal.createIndex("request_pk", Request.REQUEST, new OrderField[] { Request.REQUEST.R_ID }, true);
        public static Index REQUEST_TYPE_PK = Internal.createIndex("request_type_pk", RequestType.REQUEST_TYPE, new OrderField[] { RequestType.REQUEST_TYPE.RT_ID }, true);
        public static Index USER_DETAILS_PK = Internal.createIndex("user_details_pk", UserDetails.USER_DETAILS, new OrderField[] { UserDetails.USER_DETAILS.USER_ID }, true);
        public static Index USER_GROUP_MAPPING_PK = Internal.createIndex("user_group_mapping_pk", UserGroupMapping.USER_GROUP_MAPPING, new OrderField[] { UserGroupMapping.USER_GROUP_MAPPING.UGM_USER_ID, UserGroupMapping.USER_GROUP_MAPPING.UGM_GROUP_ID }, true);
        public static Index GROUPS_PK = Internal.createIndex("groups_pk", UserGroups.USER_GROUPS, new OrderField[] { UserGroups.USER_GROUPS.GROUP_ID }, true);
        public static Index USER_MANAGER_MAPPING_PK = Internal.createIndex("user_manager_mapping_pk", UserManagerMapping.USER_MANAGER_MAPPING, new OrderField[] { UserManagerMapping.USER_MANAGER_MAPPING.UM_MANAGER_ID, UserManagerMapping.USER_MANAGER_MAPPING.UM_USER_ID }, true);
    }
}
