/*
 * This file is generated by jOOQ.
 */
package ua.worktimekeeper.model.dayoff;


import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import ua.worktimekeeper.model.dayoff.tables.Holidays;
import ua.worktimekeeper.model.dayoff.tables.Request;
import ua.worktimekeeper.model.dayoff.tables.RequestType;
import ua.worktimekeeper.model.dayoff.tables.UserDetails;
import ua.worktimekeeper.model.dayoff.tables.UserGroupMapping;
import ua.worktimekeeper.model.dayoff.tables.UserGroups;
import ua.worktimekeeper.model.dayoff.tables.UserManagerMapping;
import ua.worktimekeeper.model.dayoff.tables.records.HolidaysRecord;
import ua.worktimekeeper.model.dayoff.tables.records.RequestRecord;
import ua.worktimekeeper.model.dayoff.tables.records.RequestTypeRecord;
import ua.worktimekeeper.model.dayoff.tables.records.UserDetailsRecord;
import ua.worktimekeeper.model.dayoff.tables.records.UserGroupMappingRecord;
import ua.worktimekeeper.model.dayoff.tables.records.UserGroupsRecord;
import ua.worktimekeeper.model.dayoff.tables.records.UserManagerMappingRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<HolidaysRecord> HOLIDAYS_PK = UniqueKeys0.HOLIDAYS_PK;
    public static final UniqueKey<RequestRecord> REQUEST_PK = UniqueKeys0.REQUEST_PK;
    public static final UniqueKey<RequestTypeRecord> REQUEST_TYPE_PK = UniqueKeys0.REQUEST_TYPE_PK;
    public static final UniqueKey<UserDetailsRecord> USER_DETAILS_PK = UniqueKeys0.USER_DETAILS_PK;
    public static final UniqueKey<UserGroupMappingRecord> USER_GROUP_MAPPING_PK = UniqueKeys0.USER_GROUP_MAPPING_PK;
    public static final UniqueKey<UserGroupsRecord> GROUPS_PK = UniqueKeys0.GROUPS_PK;
    public static final UniqueKey<UserManagerMappingRecord> USER_MANAGER_MAPPING_PK = UniqueKeys0.USER_MANAGER_MAPPING_PK;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<RequestRecord, RequestTypeRecord> REQUEST__REQUEST_FK = ForeignKeys0.REQUEST__REQUEST_FK;
    public static final ForeignKey<UserGroupMappingRecord, UserDetailsRecord> USER_GROUP_MAPPING__UGM_USER_FK = ForeignKeys0.USER_GROUP_MAPPING__UGM_USER_FK;
    public static final ForeignKey<UserGroupMappingRecord, UserGroupsRecord> USER_GROUP_MAPPING__UGM_GROUP_FK = ForeignKeys0.USER_GROUP_MAPPING__UGM_GROUP_FK;
    public static final ForeignKey<UserManagerMappingRecord, UserDetailsRecord> USER_MANAGER_MAPPING__UM_MANAGER_MAPPING_FK = ForeignKeys0.USER_MANAGER_MAPPING__UM_MANAGER_MAPPING_FK;
    public static final ForeignKey<UserManagerMappingRecord, UserDetailsRecord> USER_MANAGER_MAPPING__UM_USER_MAPPING_FK = ForeignKeys0.USER_MANAGER_MAPPING__UM_USER_MAPPING_FK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<HolidaysRecord> HOLIDAYS_PK = Internal.createUniqueKey(Holidays.HOLIDAYS, "holidays_pk", Holidays.HOLIDAYS.H_ID);
        public static final UniqueKey<RequestRecord> REQUEST_PK = Internal.createUniqueKey(Request.REQUEST, "request_pk", Request.REQUEST.R_ID);
        public static final UniqueKey<RequestTypeRecord> REQUEST_TYPE_PK = Internal.createUniqueKey(RequestType.REQUEST_TYPE, "request_type_pk", RequestType.REQUEST_TYPE.RT_ID);
        public static final UniqueKey<UserDetailsRecord> USER_DETAILS_PK = Internal.createUniqueKey(UserDetails.USER_DETAILS, "user_details_pk", UserDetails.USER_DETAILS.USER_ID);
        public static final UniqueKey<UserGroupMappingRecord> USER_GROUP_MAPPING_PK = Internal.createUniqueKey(UserGroupMapping.USER_GROUP_MAPPING, "user_group_mapping_pk", UserGroupMapping.USER_GROUP_MAPPING.UGM_USER_ID, UserGroupMapping.USER_GROUP_MAPPING.UGM_GROUP_ID);
        public static final UniqueKey<UserGroupsRecord> GROUPS_PK = Internal.createUniqueKey(UserGroups.USER_GROUPS, "groups_pk", UserGroups.USER_GROUPS.GROUP_ID);
        public static final UniqueKey<UserManagerMappingRecord> USER_MANAGER_MAPPING_PK = Internal.createUniqueKey(UserManagerMapping.USER_MANAGER_MAPPING, "user_manager_mapping_pk", UserManagerMapping.USER_MANAGER_MAPPING.UM_MANAGER_ID, UserManagerMapping.USER_MANAGER_MAPPING.UM_USER_ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<RequestRecord, RequestTypeRecord> REQUEST__REQUEST_FK = Internal.createForeignKey(ua.worktimekeeper.model.dayoff.Keys.REQUEST_TYPE_PK, Request.REQUEST, "request__request_fk", Request.REQUEST.R_TYPE_ID);
        public static final ForeignKey<UserGroupMappingRecord, UserDetailsRecord> USER_GROUP_MAPPING__UGM_USER_FK = Internal.createForeignKey(ua.worktimekeeper.model.dayoff.Keys.USER_DETAILS_PK, UserGroupMapping.USER_GROUP_MAPPING, "user_group_mapping__ugm_user_fk", UserGroupMapping.USER_GROUP_MAPPING.UGM_USER_ID);
        public static final ForeignKey<UserGroupMappingRecord, UserGroupsRecord> USER_GROUP_MAPPING__UGM_GROUP_FK = Internal.createForeignKey(ua.worktimekeeper.model.dayoff.Keys.GROUPS_PK, UserGroupMapping.USER_GROUP_MAPPING, "user_group_mapping__ugm_group_fk", UserGroupMapping.USER_GROUP_MAPPING.UGM_GROUP_ID);
        public static final ForeignKey<UserManagerMappingRecord, UserDetailsRecord> USER_MANAGER_MAPPING__UM_MANAGER_MAPPING_FK = Internal.createForeignKey(ua.worktimekeeper.model.dayoff.Keys.USER_DETAILS_PK, UserManagerMapping.USER_MANAGER_MAPPING, "user_manager_mapping__um_manager_mapping_fk", UserManagerMapping.USER_MANAGER_MAPPING.UM_MANAGER_ID);
        public static final ForeignKey<UserManagerMappingRecord, UserDetailsRecord> USER_MANAGER_MAPPING__UM_USER_MAPPING_FK = Internal.createForeignKey(ua.worktimekeeper.model.dayoff.Keys.USER_DETAILS_PK, UserManagerMapping.USER_MANAGER_MAPPING, "user_manager_mapping__um_user_mapping_fk", UserManagerMapping.USER_MANAGER_MAPPING.UM_USER_ID);
    }
}
