/*
 * This file is generated by jOOQ.
 */
package ua.worktimekeeper.model.dayoff;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ua.worktimekeeper.model.dayoff.tables.Holidays;
import ua.worktimekeeper.model.dayoff.tables.Request;
import ua.worktimekeeper.model.dayoff.tables.RequestType;
import ua.worktimekeeper.model.dayoff.tables.UserDetails;
import ua.worktimekeeper.model.dayoff.tables.UserGroupMapping;
import ua.worktimekeeper.model.dayoff.tables.UserGroups;
import ua.worktimekeeper.model.dayoff.tables.UserManagerMapping;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -667218256;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.holidays</code>.
     */
    public final Holidays HOLIDAYS = ua.worktimekeeper.model.dayoff.tables.Holidays.HOLIDAYS;

    /**
     * The table <code>public.request</code>.
     */
    public final Request REQUEST = ua.worktimekeeper.model.dayoff.tables.Request.REQUEST;

    /**
     * The table <code>public.request_type</code>.
     */
    public final RequestType REQUEST_TYPE = ua.worktimekeeper.model.dayoff.tables.RequestType.REQUEST_TYPE;

    /**
     * The table <code>public.user_details</code>.
     */
    public final UserDetails USER_DETAILS = ua.worktimekeeper.model.dayoff.tables.UserDetails.USER_DETAILS;

    /**
     * The table <code>public.user_group_mapping</code>.
     */
    public final UserGroupMapping USER_GROUP_MAPPING = ua.worktimekeeper.model.dayoff.tables.UserGroupMapping.USER_GROUP_MAPPING;

    /**
     * The table <code>public.user_groups</code>.
     */
    public final UserGroups USER_GROUPS = ua.worktimekeeper.model.dayoff.tables.UserGroups.USER_GROUPS;

    /**
     * The table <code>public.user_manager_mapping</code>.
     */
    public final UserManagerMapping USER_MANAGER_MAPPING = ua.worktimekeeper.model.dayoff.tables.UserManagerMapping.USER_MANAGER_MAPPING;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.HOLIDAYS_SEQ,
            Sequences.REQUEST_SEQ,
            Sequences.REQUEST_TYPE_SEQ,
            Sequences.USER_DETAILS_SEQ,
            Sequences.USER_GROUPS_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Holidays.HOLIDAYS,
            Request.REQUEST,
            RequestType.REQUEST_TYPE,
            UserDetails.USER_DETAILS,
            UserGroupMapping.USER_GROUP_MAPPING,
            UserGroups.USER_GROUPS,
            UserManagerMapping.USER_MANAGER_MAPPING);
    }
}
