/*
 * This file is generated by jOOQ.
 */
package ua.worktimekeeper.model.dayoff;


import javax.annotation.processing.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.holidays_seq</code>
     */
    public static final Sequence<Long> HOLIDAYS_SEQ = new SequenceImpl<Long>("holidays_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.request_seq</code>
     */
    public static final Sequence<Long> REQUEST_SEQ = new SequenceImpl<Long>("request_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.request_type_seq</code>
     */
    public static final Sequence<Long> REQUEST_TYPE_SEQ = new SequenceImpl<Long>("request_type_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.user_details_seq</code>
     */
    public static final Sequence<Long> USER_DETAILS_SEQ = new SequenceImpl<Long>("user_details_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.user_groups_seq</code>
     */
    public static final Sequence<Long> USER_GROUPS_SEQ = new SequenceImpl<Long>("user_groups_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
