/*
 * This file is generated by jOOQ.
 */
package ua.worktimekeeper.model.dayoff;


import javax.annotation.processing.Generated;

import ua.worktimekeeper.model.dayoff.tables.Holidays;
import ua.worktimekeeper.model.dayoff.tables.Request;
import ua.worktimekeeper.model.dayoff.tables.RequestType;
import ua.worktimekeeper.model.dayoff.tables.UserDetails;
import ua.worktimekeeper.model.dayoff.tables.UserGroupMapping;
import ua.worktimekeeper.model.dayoff.tables.UserGroups;
import ua.worktimekeeper.model.dayoff.tables.UserManagerMapping;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.holidays</code>.
     */
    public static final Holidays HOLIDAYS = Holidays.HOLIDAYS;

    /**
     * The table <code>public.request</code>.
     */
    public static final Request REQUEST = Request.REQUEST;

    /**
     * The table <code>public.request_type</code>.
     */
    public static final RequestType REQUEST_TYPE = RequestType.REQUEST_TYPE;

    /**
     * The table <code>public.user_details</code>.
     */
    public static final UserDetails USER_DETAILS = UserDetails.USER_DETAILS;

    /**
     * The table <code>public.user_group_mapping</code>.
     */
    public static final UserGroupMapping USER_GROUP_MAPPING = UserGroupMapping.USER_GROUP_MAPPING;

    /**
     * The table <code>public.user_groups</code>.
     */
    public static final UserGroups USER_GROUPS = UserGroups.USER_GROUPS;

    /**
     * The table <code>public.user_manager_mapping</code>.
     */
    public static final UserManagerMapping USER_MANAGER_MAPPING = UserManagerMapping.USER_MANAGER_MAPPING;
}
