/*
 * This file is generated by jOOQ.
 */
package ua.worktimekeeper.model.dayoff.tables.records;


import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import ua.worktimekeeper.model.dayoff.tables.Request;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RequestRecord extends UpdatableRecordImpl<RequestRecord> implements Record6<Long, Long, String, Timestamp, Timestamp, Long> {

    private static final long serialVersionUID = -1181596079;

    /**
     * Setter for <code>public.request.r_id</code>.
     */
    public RequestRecord setRId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.request.r_id</code>.
     */
    public Long getRId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.request.r_user_id</code>.
     */
    public RequestRecord setRUserId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.request.r_user_id</code>.
     */
    public Long getRUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.request.r_status</code>.
     */
    public RequestRecord setRStatus(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.request.r_status</code>.
     */
    public String getRStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.request.r_start_date</code>.
     */
    public RequestRecord setRStartDate(Timestamp value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.request.r_start_date</code>.
     */
    public Timestamp getRStartDate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>public.request.r_end_date</code>.
     */
    public RequestRecord setREndDate(Timestamp value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.request.r_end_date</code>.
     */
    public Timestamp getREndDate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>public.request.r_type_id</code>.
     */
    public RequestRecord setRTypeId(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.request.r_type_id</code>.
     */
    public Long getRTypeId() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, String, Timestamp, Timestamp, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, String, Timestamp, Timestamp, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Request.REQUEST.R_ID;
    }

    @Override
    public Field<Long> field2() {
        return Request.REQUEST.R_USER_ID;
    }

    @Override
    public Field<String> field3() {
        return Request.REQUEST.R_STATUS;
    }

    @Override
    public Field<Timestamp> field4() {
        return Request.REQUEST.R_START_DATE;
    }

    @Override
    public Field<Timestamp> field5() {
        return Request.REQUEST.R_END_DATE;
    }

    @Override
    public Field<Long> field6() {
        return Request.REQUEST.R_TYPE_ID;
    }

    @Override
    public Long component1() {
        return getRId();
    }

    @Override
    public Long component2() {
        return getRUserId();
    }

    @Override
    public String component3() {
        return getRStatus();
    }

    @Override
    public Timestamp component4() {
        return getRStartDate();
    }

    @Override
    public Timestamp component5() {
        return getREndDate();
    }

    @Override
    public Long component6() {
        return getRTypeId();
    }

    @Override
    public Long value1() {
        return getRId();
    }

    @Override
    public Long value2() {
        return getRUserId();
    }

    @Override
    public String value3() {
        return getRStatus();
    }

    @Override
    public Timestamp value4() {
        return getRStartDate();
    }

    @Override
    public Timestamp value5() {
        return getREndDate();
    }

    @Override
    public Long value6() {
        return getRTypeId();
    }

    @Override
    public RequestRecord value1(Long value) {
        setRId(value);
        return this;
    }

    @Override
    public RequestRecord value2(Long value) {
        setRUserId(value);
        return this;
    }

    @Override
    public RequestRecord value3(String value) {
        setRStatus(value);
        return this;
    }

    @Override
    public RequestRecord value4(Timestamp value) {
        setRStartDate(value);
        return this;
    }

    @Override
    public RequestRecord value5(Timestamp value) {
        setREndDate(value);
        return this;
    }

    @Override
    public RequestRecord value6(Long value) {
        setRTypeId(value);
        return this;
    }

    @Override
    public RequestRecord values(Long value1, Long value2, String value3, Timestamp value4, Timestamp value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RequestRecord
     */
    public RequestRecord() {
        super(Request.REQUEST);
    }

    /**
     * Create a detached, initialised RequestRecord
     */
    public RequestRecord(Long rId, Long rUserId, String rStatus, Timestamp rStartDate, Timestamp rEndDate, Long rTypeId) {
        super(Request.REQUEST);

        set(0, rId);
        set(1, rUserId);
        set(2, rStatus);
        set(3, rStartDate);
        set(4, rEndDate);
        set(5, rTypeId);
    }
}
