/*
 * This file is generated by jOOQ.
 */
package ua.worktimekeeper.model.dayoff.tables.records;


import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import ua.worktimekeeper.model.dayoff.tables.UserManagerMapping;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserManagerMappingRecord extends UpdatableRecordImpl<UserManagerMappingRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 963826572;

    /**
     * Setter for <code>public.user_manager_mapping.um_manager_id</code>.
     */
    public UserManagerMappingRecord setUmManagerId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.user_manager_mapping.um_manager_id</code>.
     */
    public Long getUmManagerId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.user_manager_mapping.um_user_id</code>.
     */
    public UserManagerMappingRecord setUmUserId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.user_manager_mapping.um_user_id</code>.
     */
    public Long getUmUserId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UserManagerMapping.USER_MANAGER_MAPPING.UM_MANAGER_ID;
    }

    @Override
    public Field<Long> field2() {
        return UserManagerMapping.USER_MANAGER_MAPPING.UM_USER_ID;
    }

    @Override
    public Long component1() {
        return getUmManagerId();
    }

    @Override
    public Long component2() {
        return getUmUserId();
    }

    @Override
    public Long value1() {
        return getUmManagerId();
    }

    @Override
    public Long value2() {
        return getUmUserId();
    }

    @Override
    public UserManagerMappingRecord value1(Long value) {
        setUmManagerId(value);
        return this;
    }

    @Override
    public UserManagerMappingRecord value2(Long value) {
        setUmUserId(value);
        return this;
    }

    @Override
    public UserManagerMappingRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserManagerMappingRecord
     */
    public UserManagerMappingRecord() {
        super(UserManagerMapping.USER_MANAGER_MAPPING);
    }

    /**
     * Create a detached, initialised UserManagerMappingRecord
     */
    public UserManagerMappingRecord(Long umManagerId, Long umUserId) {
        super(UserManagerMapping.USER_MANAGER_MAPPING);

        set(0, umManagerId);
        set(1, umUserId);
    }
}
