/*
 * This file is generated by jOOQ.
 */
package ua.worktimekeeper.model.dayoff.tables.records;


import java.sql.Date;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import ua.worktimekeeper.model.dayoff.tables.UserDetails;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDetailsRecord extends UpdatableRecordImpl<UserDetailsRecord> implements Record6<Long, String, String, String, Long, Date> {

    private static final long serialVersionUID = 72482356;

    /**
     * Setter for <code>public.user_details.user_id</code>.
     */
    public UserDetailsRecord setUserId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.user_details.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.user_details.user_name</code>.
     */
    public UserDetailsRecord setUserName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.user_details.user_name</code>.
     */
    public String getUserName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.user_details.user_email</code>.
     */
    public UserDetailsRecord setUserEmail(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.user_details.user_email</code>.
     */
    public String getUserEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.user_details.user_role</code>.
     */
    public UserDetailsRecord setUserRole(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.user_details.user_role</code>.
     */
    public String getUserRole() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.user_details.user_working_day_duration</code>.
     */
    public UserDetailsRecord setUserWorkingDayDuration(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.user_details.user_working_day_duration</code>.
     */
    public Long getUserWorkingDayDuration() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.user_details.user_start_date</code>.
     */
    public UserDetailsRecord setUserStartDate(Date value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.user_details.user_start_date</code>.
     */
    public Date getUserStartDate() {
        return (Date) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, String, Long, Date> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, String, String, String, Long, Date> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UserDetails.USER_DETAILS.USER_ID;
    }

    @Override
    public Field<String> field2() {
        return UserDetails.USER_DETAILS.USER_NAME;
    }

    @Override
    public Field<String> field3() {
        return UserDetails.USER_DETAILS.USER_EMAIL;
    }

    @Override
    public Field<String> field4() {
        return UserDetails.USER_DETAILS.USER_ROLE;
    }

    @Override
    public Field<Long> field5() {
        return UserDetails.USER_DETAILS.USER_WORKING_DAY_DURATION;
    }

    @Override
    public Field<Date> field6() {
        return UserDetails.USER_DETAILS.USER_START_DATE;
    }

    @Override
    public Long component1() {
        return getUserId();
    }

    @Override
    public String component2() {
        return getUserName();
    }

    @Override
    public String component3() {
        return getUserEmail();
    }

    @Override
    public String component4() {
        return getUserRole();
    }

    @Override
    public Long component5() {
        return getUserWorkingDayDuration();
    }

    @Override
    public Date component6() {
        return getUserStartDate();
    }

    @Override
    public Long value1() {
        return getUserId();
    }

    @Override
    public String value2() {
        return getUserName();
    }

    @Override
    public String value3() {
        return getUserEmail();
    }

    @Override
    public String value4() {
        return getUserRole();
    }

    @Override
    public Long value5() {
        return getUserWorkingDayDuration();
    }

    @Override
    public Date value6() {
        return getUserStartDate();
    }

    @Override
    public UserDetailsRecord value1(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserDetailsRecord value2(String value) {
        setUserName(value);
        return this;
    }

    @Override
    public UserDetailsRecord value3(String value) {
        setUserEmail(value);
        return this;
    }

    @Override
    public UserDetailsRecord value4(String value) {
        setUserRole(value);
        return this;
    }

    @Override
    public UserDetailsRecord value5(Long value) {
        setUserWorkingDayDuration(value);
        return this;
    }

    @Override
    public UserDetailsRecord value6(Date value) {
        setUserStartDate(value);
        return this;
    }

    @Override
    public UserDetailsRecord values(Long value1, String value2, String value3, String value4, Long value5, Date value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserDetailsRecord
     */
    public UserDetailsRecord() {
        super(UserDetails.USER_DETAILS);
    }

    /**
     * Create a detached, initialised UserDetailsRecord
     */
    public UserDetailsRecord(Long userId, String userName, String userEmail, String userRole, Long userWorkingDayDuration, Date userStartDate) {
        super(UserDetails.USER_DETAILS);

        set(0, userId);
        set(1, userName);
        set(2, userEmail);
        set(3, userRole);
        set(4, userWorkingDayDuration);
        set(5, userStartDate);
    }
}
