/*
 * This file is generated by jOOQ.
 */
package ua.worktimekeeper.model.dayoff.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Request implements Serializable {

    private static final long serialVersionUID = 1012224672;

    private final Long      rId;
    private final Long      rUserId;
    private final String    rStatus;
    private final Timestamp rStartDate;
    private final Timestamp rEndDate;
    private final Long      rTypeId;

    public Request(Request value) {
        this.rId = value.rId;
        this.rUserId = value.rUserId;
        this.rStatus = value.rStatus;
        this.rStartDate = value.rStartDate;
        this.rEndDate = value.rEndDate;
        this.rTypeId = value.rTypeId;
    }

    public Request(
        Long      rId,
        Long      rUserId,
        String    rStatus,
        Timestamp rStartDate,
        Timestamp rEndDate,
        Long      rTypeId
    ) {
        this.rId = rId;
        this.rUserId = rUserId;
        this.rStatus = rStatus;
        this.rStartDate = rStartDate;
        this.rEndDate = rEndDate;
        this.rTypeId = rTypeId;
    }

    public Long getRId() {
        return this.rId;
    }

    public Long getRUserId() {
        return this.rUserId;
    }

    public String getRStatus() {
        return this.rStatus;
    }

    public Timestamp getRStartDate() {
        return this.rStartDate;
    }

    public Timestamp getREndDate() {
        return this.rEndDate;
    }

    public Long getRTypeId() {
        return this.rTypeId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Request (");

        sb.append(rId);
        sb.append(", ").append(rUserId);
        sb.append(", ").append(rStatus);
        sb.append(", ").append(rStartDate);
        sb.append(", ").append(rEndDate);
        sb.append(", ").append(rTypeId);

        sb.append(")");
        return sb.toString();
    }
}
