/*
 * This file is generated by jOOQ.
 */
package ua.worktimekeeper.model.dayoff.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDetails implements Serializable {

    private static final long serialVersionUID = 875894990;

    private final Long   userId;
    private final String userName;
    private final String userEmail;
    private final String userRole;
    private final Long   userWorkingDayDuration;
    private final Date   userStartDate;

    public UserDetails(UserDetails value) {
        this.userId = value.userId;
        this.userName = value.userName;
        this.userEmail = value.userEmail;
        this.userRole = value.userRole;
        this.userWorkingDayDuration = value.userWorkingDayDuration;
        this.userStartDate = value.userStartDate;
    }

    public UserDetails(
        Long   userId,
        String userName,
        String userEmail,
        String userRole,
        Long   userWorkingDayDuration,
        Date   userStartDate
    ) {
        this.userId = userId;
        this.userName = userName;
        this.userEmail = userEmail;
        this.userRole = userRole;
        this.userWorkingDayDuration = userWorkingDayDuration;
        this.userStartDate = userStartDate;
    }

    public Long getUserId() {
        return this.userId;
    }

    public String getUserName() {
        return this.userName;
    }

    public String getUserEmail() {
        return this.userEmail;
    }

    public String getUserRole() {
        return this.userRole;
    }

    public Long getUserWorkingDayDuration() {
        return this.userWorkingDayDuration;
    }

    public Date getUserStartDate() {
        return this.userStartDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserDetails (");

        sb.append(userId);
        sb.append(", ").append(userName);
        sb.append(", ").append(userEmail);
        sb.append(", ").append(userRole);
        sb.append(", ").append(userWorkingDayDuration);
        sb.append(", ").append(userStartDate);

        sb.append(")");
        return sb.toString();
    }
}
