/*
 * This file is generated by jOOQ.
 */
package ua.worktimekeeper.model.dayoff.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserGroupMapping implements Serializable {

    private static final long serialVersionUID = 2083871313;

    private final Long ugmUserId;
    private final Long ugmGroupId;

    public UserGroupMapping(UserGroupMapping value) {
        this.ugmUserId = value.ugmUserId;
        this.ugmGroupId = value.ugmGroupId;
    }

    public UserGroupMapping(
        Long ugmUserId,
        Long ugmGroupId
    ) {
        this.ugmUserId = ugmUserId;
        this.ugmGroupId = ugmGroupId;
    }

    public Long getUgmUserId() {
        return this.ugmUserId;
    }

    public Long getUgmGroupId() {
        return this.ugmGroupId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserGroupMapping (");

        sb.append(ugmUserId);
        sb.append(", ").append(ugmGroupId);

        sb.append(")");
        return sb.toString();
    }
}
