/*
 * This file is generated by jOOQ.
 */
package ua.worktimekeeper.model.dayoff.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserGroups implements Serializable {

    private static final long serialVersionUID = -1761542421;

    private final Long   groupId;
    private final String groupName;
    private final String groupDescription;

    public UserGroups(UserGroups value) {
        this.groupId = value.groupId;
        this.groupName = value.groupName;
        this.groupDescription = value.groupDescription;
    }

    public UserGroups(
        Long   groupId,
        String groupName,
        String groupDescription
    ) {
        this.groupId = groupId;
        this.groupName = groupName;
        this.groupDescription = groupDescription;
    }

    public Long getGroupId() {
        return this.groupId;
    }

    public String getGroupName() {
        return this.groupName;
    }

    public String getGroupDescription() {
        return this.groupDescription;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserGroups (");

        sb.append(groupId);
        sb.append(", ").append(groupName);
        sb.append(", ").append(groupDescription);

        sb.append(")");
        return sb.toString();
    }
}
