/*
 * This file is generated by jOOQ.
 */
package ua.worktimekeeper.model.dayoff.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserManagerMapping implements Serializable {

    private static final long serialVersionUID = 280801843;

    private final Long umManagerId;
    private final Long umUserId;

    public UserManagerMapping(UserManagerMapping value) {
        this.umManagerId = value.umManagerId;
        this.umUserId = value.umUserId;
    }

    public UserManagerMapping(
        Long umManagerId,
        Long umUserId
    ) {
        this.umManagerId = umManagerId;
        this.umUserId = umUserId;
    }

    public Long getUmManagerId() {
        return this.umManagerId;
    }

    public Long getUmUserId() {
        return this.umUserId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserManagerMapping (");

        sb.append(umManagerId);
        sb.append(", ").append(umUserId);

        sb.append(")");
        return sb.toString();
    }
}
