/*
 * This file is generated by jOOQ.
 */
package ua.worktimekeeper.model.dayoff.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ua.worktimekeeper.model.dayoff.Indexes;
import ua.worktimekeeper.model.dayoff.Keys;
import ua.worktimekeeper.model.dayoff.Public;
import ua.worktimekeeper.model.dayoff.tables.records.UserGroupsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserGroups extends TableImpl<UserGroupsRecord> {

    private static final long serialVersionUID = 723359393;

    /**
     * The reference instance of <code>public.user_groups</code>
     */
    public static final UserGroups USER_GROUPS = new UserGroups();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserGroupsRecord> getRecordType() {
        return UserGroupsRecord.class;
    }

    /**
     * The column <code>public.user_groups.group_id</code>.
     */
    public final TableField<UserGroupsRecord, Long> GROUP_ID = createField(DSL.name("group_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.user_groups.group_name</code>.
     */
    public final TableField<UserGroupsRecord, String> GROUP_NAME = createField(DSL.name("group_name"), org.jooq.impl.SQLDataType.VARCHAR(150).nullable(false), this, "");

    /**
     * The column <code>public.user_groups.group_description</code>.
     */
    public final TableField<UserGroupsRecord, String> GROUP_DESCRIPTION = createField(DSL.name("group_description"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>public.user_groups</code> table reference
     */
    public UserGroups() {
        this(DSL.name("user_groups"), null);
    }

    /**
     * Create an aliased <code>public.user_groups</code> table reference
     */
    public UserGroups(String alias) {
        this(DSL.name(alias), USER_GROUPS);
    }

    /**
     * Create an aliased <code>public.user_groups</code> table reference
     */
    public UserGroups(Name alias) {
        this(alias, USER_GROUPS);
    }

    private UserGroups(Name alias, Table<UserGroupsRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserGroups(Name alias, Table<UserGroupsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> UserGroups(Table<O> child, ForeignKey<O, UserGroupsRecord> key) {
        super(child, key, USER_GROUPS);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.GROUPS_PK);
    }

    @Override
    public UniqueKey<UserGroupsRecord> getPrimaryKey() {
        return Keys.GROUPS_PK;
    }

    @Override
    public List<UniqueKey<UserGroupsRecord>> getKeys() {
        return Arrays.<UniqueKey<UserGroupsRecord>>asList(Keys.GROUPS_PK);
    }

    @Override
    public UserGroups as(String alias) {
        return new UserGroups(DSL.name(alias), this);
    }

    @Override
    public UserGroups as(Name alias) {
        return new UserGroups(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserGroups rename(String name) {
        return new UserGroups(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserGroups rename(Name name) {
        return new UserGroups(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
